Repository Skyscanner/backpack-foundations, pull requests merged in 2025-06, with the labels that each got.

#447 [CLOV 315]Update grey 05 token
  packages/bpk-foundations-android/tokens/base.raw.android.json
  packages/bpk-foundations-common/base/colors/aliases.json
  packages/bpk-foundations-ios/tokens/base.ios.json
  packages/bpk-foundations-ios/tokens/base.raw.ios.json
  packages/bpk-foundations-web/tokens/base.common.js
  packages/bpk-foundations-web/tokens/base.default.scss
  packages/bpk-foundations-web/tokens/base.es6.d.ts
  packages/bpk-foundations-web/tokens/base.es6.js
  packages/bpk-foundations-web/tokens/base.raw.json
  packages/bpk-foundations-web/tokens/base.scss
Labels: minor

#446 [CLOV289][Fix Alert]Replace gulp-jsonlint with eslint
  .eslintrc.json
  package-lock.json
  package.json
  packages/bpk-foundations-android/gulpfile.mjs
  packages/bpk-foundations-common/base/colors/chip.json
  packages/bpk-foundations-common/base/colors/navigation-tab.json
  packages/bpk-foundations-common/base/colors/rating-bar.json
  packages/bpk-foundations-common/base/colors/skeleton.json
  packages/bpk-foundations-ios/gulpfile.mjs
  packages/bpk-foundations-web/gulpfile.mjs
Labels: bug, minor

#457 Donburi/don 1767 remove deprecated tokens test
  packages/bpk-foundations-android/tokens/base.raw.android.json
  packages/bpk-foundations-common/base/colors/base.json
  packages/bpk-foundations-ios/tokens/base.ios.json
  packages/bpk-foundations-ios/tokens/base.raw.ios.json
  packages/bpk-foundations-web/tokens/base.common.js
  packages/bpk-foundations-web/tokens/base.default.scss
  packages/bpk-foundations-web/tokens/base.es6.d.ts
  packages/bpk-foundations-web/tokens/base.es6.js
  packages/bpk-foundations-web/tokens/base.raw.json
  packages/bpk-foundations-web/tokens/base.scss
Labels: major
